@baseUrl = http://localhost:4000

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/create-checkout-session
Content-Type: application/json
Accept: application/json
withCredentials: true

{ "payload": {
    "name":"jason",
    "email":"test@email.com",
    "phoneNumber":"604-572-4747",
    "pickupDate":"2023/01/12",
    "items":[{
        "_id": "6305bff7b948507e58b66c63",
        "name":"Brisket",
        "stock":3,
        "description":"test",
        "priceStr":"150.00",
        "quantity":3
    },
    {
        "_id":"6305c020b948507e58b66c64",
        "name":"Pork",
        "stock":3,
        "description":"test",
        "priceStr":"100.00",
        "quantity":1
    }]
    }
}
